### ISSUE TITLE
Error: gcode command M140 already registered

### ISSUE THREAD

**Issue by bthome** [seanauff/dwc2-klipper#1]
Thank you for putting this together.  I'm using your octoprint-klipper and wanted to try this one out in comparison.  Getting an error and would appreciate any insight.  My config file works with octoprint-klipper so I think that is good.  Not sure what to do next.

INFO:root:Starting Klippy...
WARNING:root:No log file specified! Severe timing issues may result!
INFO:root:Start printer at Mon May 11 20:06:12 2020 (1589245572.3 439459.2)
ERROR:root:Config error
Traceback (most recent call last):
  File "/home/dwc2-klipper/klipper/klippy/klippy.py", line 134, in _connect
    self._read_config()
  File "/home/dwc2-klipper/klipper/klippy/klippy.py", line 127, in _read_config
    self.try_load_module(config, section_config.get_name())
  File "/home/dwc2-klipper/klipper/klippy/klippy.py", line 116, in try_load_module
    self.objects[section] = init_func(config.getsection(section))
  File "/home/dwc2-klipper/klipper/klippy/extras/heater_bed.py", line 31, in load_config
    return PrinterHeaterBed(config)
  File "/home/dwc2-klipper/klipper/klippy/extras/heater_bed.py", line 16, in __init__
    gcode.register_command("M140", self.cmd_M140)
  File "/home/dwc2-klipper/klipper/klippy/gcode.py", line 72, in register_command
    "gcode command %s already registered" % (cmd,))
Error: gcode command M140 already registered

**Comment by seanauff** [comment]
Not totally sure, especially since your config file works with the octoprint version. I have been meaning to update the image since it is pretty old at this point and there have been a few updates to both dwc2 and klipper. Once I get it updated try it then.

**Comment by bthome** [comment]
Thank You.  I prefer wrapping these things in docker containers and running them that way over direct installs.

I started looking into these as well.
[https://github.com/meteyou/mainsail](https://github.com/meteyou/mainsail)
[https://github.com/FuraX49/klippy-web-control](https://github.com/FuraX49/klippy-web-control)

**Comment by seanauff** [comment]
Totally agreed on the use of Docker for things like this.

I updated the repo (on the `dev-update` branch) and pushed new images to DockerHub (tags `dev-arm` and `dev-amd64`). Some recent changes to Klipper broke the dwc2 translator but someone made a fork (discussion [here](https://github.com/Stephan3/dwc2-for-klipper/issues/73)). I was able to load the web interface no problem but I wont be able to do any print testing for a bit, so if you are able to do that it would be great feedback. I'll leave all the changes on the `dev-update` branch until that's confirmed.

I looked at some of those other controllers - I might have to make some more images to try them out!

**Comment by bthome** [comment]
Worked like a champ!  Thank You!

I am running a little different of a configuration and would appreciate it if you could add a feature to your image.  I am running my docker from a server and connecting to my printer via Pi over WiFi.  So using Socat->ser2net.  I was able to inject Socat into your image and completed a print.

Would it be possible to add "apt-get socat" to your image?

I'll keep an eye on your repo to see if you add any additional variation to your klipper dockers.

**Comment by seanauff** [comment]
Great, thanks for confirming! And sure, I can go ahead and add socat to the image. Since you confirmed you can print, I'll merge the dev branch into master and update all the images.

**Comment by bthome** [comment]
Excellent.  Looking forward to it.

Based on some Discord chats I saw it looks like DWC2 is going to deprecate in favor of mainsail soon (in alpha\beta).  Looking at mainsail it will definitely require a docker since it contains more than just a couple .py files.  :-)

**Comment by seanauff** [comment]
Interesting, guess I'll be making a Mainsail image sooner rather than later. New images are up, under `arm` and `amd64` tags now. Happy printing!
